### ISSUE TITLE
hw 5

### ISSUE THREAD

**Issue by Rachel-Zeng** [Rachel-Zeng/hw-5#1]
each time I run my code in Jupyter will end up with different result with same input. and sometimes just nothing comes out but keep making a new cell. I was not able to check my work bc my output was reasonable and then became weird without changing anything(like probably walk away for a minute and come back with different result) @tangyao1123
0.425, 0.06, 0.08

**Comment by tangyao1123** [comment]
graded. Comments are sent via email
